baseURL = https://www.americanexpress.com/fr-fr/?inav=NavLogo
homePageTitle = American Express FR : Cartes de Paiement & Services Privilégiés
CartesAmexTitle = Cartes American Express | AMEX FR
GoldAmexTitle = Gold American Express: La Carte à la Hauteur de Votre Quotidien
CarteGoldAmexTitle = American Express - CARTE GOLD AMERICAN EXPRESS
browser = chrome
fName_P=abcnd
lName_P=bnbcvd
dob_P=10/07/1990
email_P=abc@xyz.com
phone_P=0665557777
cnfrm_msg = Vos informations personnelles
fName_N=123
lName_N=567
dob_N=10/07/2010
email_N=abcxyz.com
phone_N=0655577
civilite_emsg = Merci de préciser votre civilité.
fName_emsg = Prénom obligatoire.
lName_emsg = Nom obligatoire.
dob_emsg = Vous devez avoir plus de 18 ans.
email_emsg = Merci de vérifier le format de votre adresse email (exemple : nom@domaine.fr). Les caractères autorisés sont : lettres, chiffres, tirets (_-), arobase (@), et point (.).
phone_emsg = Téléphone mobile obligatoire en chiffres uniquement et sans espaces. Exemple France, Guadeloupe, Martinique, Guyane, La Réunion, Saint- Barthélemy, Saint Martin, Mayotte: - 0612345678 - 0712345678 IMPORTANT : Pour tout autre pays ou région, dont Polynésie Française et Nouvelle Calédonie, merci de sélectionner l\u2019indicatif du territoire correspondant et saisir le numéro de mobile sans le préfixe « 0 » au début.
cnfrm_emsg = Veuillez corriger les erreurs ci-dessus pour continuer.